name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Test CLI functionality
      run: |
        # Test help command
        dbtlist --help
        
        # Test with sample data
        dbtlist -s "state:modified" data/jaffe_shop_duckdb/old.json data/jaffe_shop_duckdb/new.json
        
        # Test state:modified+ selector
        dbtlist -s "state:modified+" data/jaffe_shop_duckdb/old.json data/jaffe_shop_duckdb/new.json

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Format check with black
      run: |
        black --check dbtlist/ tests/
    
    - name: Lint with flake8
      run: |
        flake8 dbtlist/ tests/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Type check with mypy
      run: |
        mypy dbtlist/ --ignore-missing-imports